### ISSUE TITLE
Error when load wasm file 

### ISSUE THREAD

**Issue by csd-rd** [yusuf8ahmed/Wasmite#4]
Hi Yusuf,

I generate a wasm file using emscripten with option ENVIRONMENT=web
I try to use your solution to run UT, when I load the model, I have this message 

None
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    class Test(WasmiteCase):
  File "main.py", line 32, in Test
    module = WasiModule(fileWasm)
  File "/home/build/.local/lib/python3.8/site-packages/wasmite/globals.py", line 33, in __init__
    self._import_module()
  File "/home/build/.local/lib/python3.8/site-packages/wasmite/wasi.py", line 20, in _import_module
    self.import_object = wasi_env.generate_import_object(self.store, wasi_version)
TypeError: argument 'wasi_version': 'NoneType' object cannot be interpreted as an integer

**Comment by csd-rd** [comment]
Python version : Python 3.8.5 (default, Jul 28 2020, 12:59:40)

> Hi Yusuf,
> 
> I generate a wasm file using emscripten with option ENVIRONMENT=web
> I try to use your solution to run UT, when I load the model, I have this message
> 
> None
> Traceback (most recent call last):
> File "main.py", line 30, in
> class Test(WasmiteCase):
> File "main.py", line 32, in Test
> module = WasiModule(fileWasm)
> File "/home/build/.local/lib/python3.8/site-packages/wasmite/globals.py", line 33, in **init**
> self._import_module()
> File "/home/build/.local/lib/python3.8/site-packages/wasmite/wasi.py", line 20, in _import_module
> self.import_object = wasi_env.generate_import_object(self.store, wasi_version)
> TypeError: argument 'wasi_version': 'NoneType' object cannot be interpreted as an integer

**Comment by csd-rd** [comment]
![Wasm](https://user-images.githubusercontent.com/45396572/109813420-9b8cca80-7c2d-11eb-9b08-c97ef7922572.png)
